name: countapp
description: 'A simple application to help users keep track of their counts effortlessly.'
publish_to: 'none'
version: 1.3.2

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  connectivity_plus: ^6.1.1
  file_picker: ^8.1.4
  fl_chart: ^0.69.2
  flutter:
    sdk: flutter
  flutter_layout_grid: ^2.0.7
  hive_ce: ^2.7.0+1
  hive_ce_flutter: ^2.1.0
  http: ^1.2.2
  intl: ^0.19.0
  package_info_plus: ^8.1.1
  permission_handler: ^11.3.1
  provider: ^6.1.2
  pub_semver: ^2.1.5
  toastification: ^2.3.0
  url_launcher: ^6.3.1
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.13
  flutter_launcher_icons: 0.14.1
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.7.0
  lint: ^2.3.0
  msix: ^3.16.8
  package_rename: ^1.7.1
  sort_pubspec_dependencies: ^0.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/android/icon.png

msix_config:
  display_name: Count App
  publisher_display_name: KingBenny101
  identity_name: com.kingbenny101.countapp
  logo_path: assets/icon/windows/icon.png