// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:countapp/counters/series_counter/series_counter.dart';
import 'package:countapp/counters/tap_counter/tap_counter.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(SeriesCounterAdapter());
    registerAdapter(TapCounterAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(SeriesCounterAdapter());
    registerAdapter(TapCounterAdapter());
  }
}
